/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.Database;

import Networkingapp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author peichen
 */
public class DatabaseLogin extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseLogin
     */
    public DatabaseLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel = new javax.swing.JPanel();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        oracle_password = new javax.swing.JPasswordField();
        oracle_username = new javax.swing.JFormattedTextField();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oracle Database User Login");
        getContentPane().setLayout(null);

        bg_panel.setBackground(new java.awt.Color(255, 255, 255));

        username_label.setText("Oracle Username:");

        password_label.setText("Oracle Password:");

        login_button.setText("Login");
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_buttonMousePressed(evt);
            }
        });

        oracle_password.setText("a12345678");
        oracle_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oracle_passwordMousePressed(evt);
            }
        });

        oracle_username.setText("ora_a1a1a");
        oracle_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oracle_usernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oracle_usernameMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout bg_panelLayout = new javax.swing.GroupLayout(bg_panel);
        bg_panel.setLayout(bg_panelLayout);
        bg_panelLayout.setHorizontalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_panelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username_label)
                            .addComponent(password_label))
                        .addGap(18, 18, 18)
                        .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oracle_username)
                            .addComponent(oracle_password, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                    .addGroup(bg_panelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(login_button)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        bg_panelLayout.setVerticalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_label)
                    .addComponent(oracle_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label)
                    .addComponent(oracle_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login_button)
                .addGap(20, 20, 20))
        );

        getContentPane().add(bg_panel);
        bg_panel.setBounds(40, 40, 270, 160);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Networkingapp/Pictures/oracle-login.png"))); // NOI18N
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 350, 240);

        setSize(new java.awt.Dimension(346, 263));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private Connection con;

    // user is allowed 3 login attempts
    private int loginAttempts = 0;
    private JFrame mainFrame;
    
    
  
    private void oracle_usernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oracle_usernameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_oracle_usernameMouseEntered

    private void oracle_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oracle_usernameMouseClicked
        oracle_username.setText("");
    }//GEN-LAST:event_oracle_usernameMouseClicked

    private void oracle_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oracle_passwordMousePressed
        oracle_password.setText("");
    }//GEN-LAST:event_oracle_passwordMousePressed

    private void login_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMousePressed
        // TODO add your handling code here:
        DatabaseManager dbm = DatabaseManager.getInstance();
        if(dbm.startConnection(oracle_username.getText(), oracle_password.getText())){
            // if the username and password are valid,
            // remove the login dialog
            dispose();
            new FirstPage().setVisible(true);
        }
        else{
            loginAttempts++;
            if (loginAttempts >= 3) {
                dispose();
                System.exit(-1);
            } else {
                oracle_password.setText("");
            }
        }
    }//GEN-LAST:event_login_buttonMousePressed

    /**
     * @param args the command line arguments
     */
  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_label;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField oracle_password;
    private javax.swing.JFormattedTextField oracle_username;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
