/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.Database;


import Networkingapp.Login;
import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author peichen
 */
public class DatabaseLogin extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseLogin
     */
    public DatabaseLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conFail_frame = new javax.swing.JInternalFrame();
        conFail_label = new javax.swing.JLabel();
        conFailPic_label = new javax.swing.JLabel();
        conFail_button = new javax.swing.JButton();
        bg_panel = new javax.swing.JPanel();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        oracle_password = new javax.swing.JPasswordField();
        oracle_username = new javax.swing.JFormattedTextField();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oracle Database User Login");
        getContentPane().setLayout(null);

        conFail_frame.setClosable(true);
        conFail_frame.setTitle("Warnning!");
        conFail_frame.setVisible(false);
        conFail_frame.getContentPane().setLayout(null);

        conFail_label.setText("Connection Faild.");
        conFail_frame.getContentPane().add(conFail_label);
        conFail_label.setBounds(60, 30, 120, 20);

        conFailPic_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Networkingapp/Pictures/connectionFail-symbol.png"))); // NOI18N
        conFail_frame.getContentPane().add(conFailPic_label);
        conFailPic_label.setBounds(20, 20, 30, 40);

        conFail_button.setText("Ok");
        conFail_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conFail_buttonMouseClicked(evt);
            }
        });
        conFail_frame.getContentPane().add(conFail_button);
        conFail_button.setBounds(70, 60, 75, 30);

        getContentPane().add(conFail_frame);
        conFail_frame.setBounds(60, 60, 230, 160);

        bg_panel.setBackground(new java.awt.Color(255, 255, 255));
        bg_panel.setLayout(null);

        username_label.setText("Oracle Username:");
        bg_panel.add(username_label);
        username_label.setBounds(22, 23, 110, 16);

        password_label.setText("Oracle Password:");
        bg_panel.add(password_label);
        password_label.setBounds(25, 72, 107, 16);

        login_button.setText("Login");
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_buttonMousePressed(evt);
            }
        });
        bg_panel.add(login_button);
        login_button.setBounds(95, 111, 79, 29);

        oracle_password.setText("a12345678");
        oracle_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oracle_passwordMousePressed(evt);
            }
        });
        bg_panel.add(oracle_password);
        oracle_password.setBounds(150, 67, 92, 26);

        oracle_username.setText("ora_a1a1a");
        oracle_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oracle_usernameMouseClicked(evt);
            }
        });
        bg_panel.add(oracle_username);
        oracle_username.setBounds(150, 18, 92, 26);

        getContentPane().add(bg_panel);
        bg_panel.setBounds(40, 40, 270, 160);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Networkingapp/Pictures/oracle-login.png"))); // NOI18N
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 350, 240);

        setSize(new java.awt.Dimension(346, 263));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    // user is allowed 3 login attempts
    private int loginAttempts = 0;
    private JFrame mainFrame;
    
    
  
    private void oracle_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oracle_usernameMouseClicked
        oracle_username.setText("");
    }//GEN-LAST:event_oracle_usernameMouseClicked

    private void oracle_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oracle_passwordMousePressed
        oracle_password.setText("");
    }//GEN-LAST:event_oracle_passwordMousePressed

    private void login_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMousePressed
        // TODO add your handling code here:
        
//        oracle_password.setText(""); // TestDelete
//        oracle_username.setText(""); // TestDelete
        
        OracleDatabaseConnect dbm = OracleDatabaseConnect.getInstance();
        if(dbm.startConnection(oracle_username.getText(), oracle_password.getText())){
            // if the username and password are valid,
            // remove the login dialog
            dispose();
            new Login().setVisible(true);
        }
        else{
            loginAttempts++;
            if (loginAttempts >= 3) {
                dispose();
                System.out.println("Oracle Login Failed.");
                System.exit(-1);
                
            } else {
                oracle_password.setText("");
                conFail_frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_login_buttonMousePressed

    private void conFail_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conFail_buttonMouseClicked
        // TODO add your handling code here:
        conFail_frame.setVisible(false);
    }//GEN-LAST:event_conFail_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_label;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JLabel conFailPic_label;
    private javax.swing.JButton conFail_button;
    private javax.swing.JInternalFrame conFail_frame;
    private javax.swing.JLabel conFail_label;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField oracle_password;
    private javax.swing.JFormattedTextField oracle_username;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
