/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp;

import Networkingapp.Database.DatabaseManager;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
/**
 *
 * @author Jade
 */
public class CreateUser extends javax.swing.JFrame {
     private Connection con;
//    String newUserID;
//    String newUserPassword;
//    String newUserName;
//    String newUserAge;
//    String newUserLocation;
//    String newUserGender;

    /**
     * Creates new form CreateUser
     */
    public CreateUser() {
        initComponents();
        
       
    }
    
    private void createNewUser(String uId, String upassword) {
        if (uId.length() > 7) {
            
        }
        System.out.println("insert into App_User values ('u"
                + uId + "','" + upassword + "')");
        String createU = "insert into App_User values ('u"
                + uId + "','" + upassword + "')";
        // uId = "u" + uId;
        DatabaseManager dbm = DatabaseManager.getInstance();
        try {
            dbm.updateStatement(createU);
            
            } 
        
        catch (SQLException ex) {
            Logger.getLogger(CreateUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void createNewUserProfile(String uid, String uName, String uAge, String uLoc, String uGender) {
        DatabaseManager dbm = DatabaseManager.getInstance();
        String profileID = "p" + uid;
        uid = "u" + uid;
        String createProfile = "INSERT INTO PROFILE values('" + profileID + "','" + uName 
                + "','" + uAge + "','" + uLoc + "','" + uGender + "','" + uid + "')";
        System.out.println("INSERT INTO PROFILE values('" + profileID + "','" + uName 
                + "','" + uAge + "','" + uLoc + "','" + uGender + "','" + uid + "')");
        try {
//            dbm.updateWithPrepareStatement(
//                    "INSERT INTO Profiles(profile_ID,profile_name,profile_age,profile_location,profile_gender,user_ID)" 
//                    + "VALUES(?,?)" , profileID, uName, uAge, uLoc, uGender, uid);
            //System.out.println();
            dbm.updateStatement(createProfile);
            } 
        catch (SQLException ex) {
            Logger.getLogger(CreateUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uHometown = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uPassword = new javax.swing.JPasswordField();
        uGender = new javax.swing.JComboBox<>();
        signUpButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UserIDjText = new javax.swing.JTextField();

        jLabel1.setText("Welcome, new friend!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to new world!");
        setBackground(java.awt.Color.pink);
        getContentPane().setLayout(null);

        uName.setText("How should we call you?");
        uName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uNameFocusGained(evt);
            }
        });
        uName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uNameMouseClicked(evt);
            }
        });
        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });
        getContentPane().add(uName);
        uName.setBounds(310, 119, 203, 36);

        jLabel2.setText("Your Password*:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(156, 87, 102, 16);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(805, 301, 0, 0);

        jLabel4.setText("Your Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(169, 127, 73, 16);

        uHometown.setText("Where are you from?");
        uHometown.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uHometownFocusGained(evt);
            }
        });
        uHometown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uHometownActionPerformed(evt);
            }
        });
        getContentPane().add(uHometown);
        uHometown.setBounds(310, 209, 203, 36);

        jLabel5.setText("Your Age:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(181, 171, 61, 16);

        uAge.setText("How old are you?");
        uAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uAgeFocusGained(evt);
            }
        });
        uAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uAgeActionPerformed(evt);
            }
        });
        getContentPane().add(uAge);
        uAge.setBounds(310, 161, 203, 36);

        jLabel6.setText("Your Location:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(156, 219, 91, 16);

        jLabel7.setText("Your Gender:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(166, 280, 81, 16);

        uPassword.setText("jPasswordField1");
        uPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uPasswordFocusGained(evt);
            }
        });
        getContentPane().add(uPassword);
        uPassword.setBounds(310, 82, 203, 26);

        uGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Secret" }));
        uGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uGenderActionPerformed(evt);
            }
        });
        getContentPane().add(uGender);
        uGender.setBounds(363, 276, 100, 27);

        signUpButton.setText("Sign Up!");
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
        });
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton);
        signUpButton.setBounds(275, 334, 96, 29);

        jLabel8.setText("Hello New Friend! Tell us about yourself");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(84, 0, 335, 40);

        jLabel9.setText("Your User Id*:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(156, 48, 87, 16);

        UserIDjText.setText("7 digits");
        UserIDjText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserIDjTextFocusGained(evt);
            }
        });
        UserIDjText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserIDjTextMouseClicked(evt);
            }
        });
        UserIDjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDjTextActionPerformed(evt);
            }
        });
        getContentPane().add(UserIDjText);
        UserIDjText.setBounds(310, 48, 203, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uAgeActionPerformed

    private void uGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uGenderActionPerformed

    private void uHometownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uHometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uHometownActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void uNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameMouseClicked

    private void UserIDjTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserIDjTextMouseClicked
        // TODO add your handling code here:
        UserIDjText.setText("");
    }//GEN-LAST:event_UserIDjTextMouseClicked

    private void UserIDjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDjTextActionPerformed

    private void UserIDjTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserIDjTextFocusGained
        // TODO add your handling code here:
        // jtextField.setText(""); 
        UserIDjText.setText("");
    }//GEN-LAST:event_UserIDjTextFocusGained

    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameActionPerformed

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseClicked
        // TODO add your handling code here:
        String iUloc = uHometown.getText();
        String iUID = UserIDjText.getText();
        String iUpassword = String.valueOf(uPassword.getPassword());
        String iUname = uName.getText();
        String iUage = uAge.getText();
        String iUgender = String.valueOf(uGender.getSelectedItem());         
        createNewUser(iUID, iUpassword);
        createNewUserProfile (iUID,iUname , iUage, iUloc, iUgender);
        System.out.println(iUID + " " + iUpassword + " "+ iUname + iUgender);
    }//GEN-LAST:event_signUpButtonMouseClicked

    private void uPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uPasswordFocusGained
        // TODO add your handling code here:
        uPassword.setText("");
    }//GEN-LAST:event_uPasswordFocusGained

    private void uNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uNameFocusGained
        uName.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameFocusGained

    private void uAgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uAgeFocusGained
        // TODO add your handling code here:
        uAge.setText("");
    }//GEN-LAST:event_uAgeFocusGained

    private void uHometownFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uHometownFocusGained
        // TODO add your handling code here:
        uHometown.setText("");
    }//GEN-LAST:event_uHometownFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UserIDjText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField uAge;
    private javax.swing.JComboBox<String> uGender;
    private javax.swing.JTextField uHometown;
    private javax.swing.JTextField uName;
    private javax.swing.JPasswordField uPassword;
    // End of variables declaration//GEN-END:variables
}
