/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp;

/**
 *
 * @author Linda <lujiecanada@gmail.com>
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    public FirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLine1 = new javax.swing.JLabel();
        textLine2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        textLine1.setBackground(new java.awt.Color(0, 0, 0));
        textLine1.setFont(new java.awt.Font("Myanmar MN", 0, 20)); // NOI18N
        textLine1.setForeground(new java.awt.Color(0, 51, 51));
        textLine1.setText("Make Today So AWESOME");
        getContentPane().add(textLine1);
        textLine1.setBounds(70, 150, 280, 60);

        textLine2.setBackground(new java.awt.Color(0, 0, 0));
        textLine2.setFont(new java.awt.Font("Myanmar MN", 0, 20)); // NOI18N
        textLine2.setForeground(new java.awt.Color(0, 51, 51));
        textLine2.setText("Yesterday gets Jealous ");
        getContentPane().add(textLine2);
        textLine2.setBounds(80, 180, 250, 60);

        loginButton.setBackground(new java.awt.Color(255, 168, 208));
        loginButton.setFont(new java.awt.Font("Myanmar MN", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.setBorderPainted(false);
        loginButton.setOpaque(true);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(60, 360, 100, 40);

        signUpButton.setBackground(new java.awt.Color(255, 168, 208));
        signUpButton.setFont(new java.awt.Font("Myanmar MN", 1, 18)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Sign Up");
        signUpButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signUpButton.setBorderPainted(false);
        signUpButton.setOpaque(true);
        signUpButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpButtonFocusGained(evt);
            }
        });
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
        });
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton);
        signUpButton.setBounds(230, 360, 100, 40);

        backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Networkingapp/Pictures/FirstPage.jpg"))); // NOI18N
        backgroud.setPreferredSize(new java.awt.Dimension(790, 534));
        getContentPane().add(backgroud);
        backgroud.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(800, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void signUpButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonFocusGained

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
        login.setSize(620,370);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_loginButtonMouseClicked

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseClicked
        this.setVisible(false);
        CreateUser createUser = new CreateUser();
        createUser.setVisible(true);
        createUser.setSize(620,370);
        createUser.setLocationRelativeTo(null);
    }//GEN-LAST:event_signUpButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroud;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel textLine1;
    private javax.swing.JLabel textLine2;
    // End of variables declaration//GEN-END:variables
}
