/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.Supervisor;

import Networkingapp.Database.DatabaseManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author lisiyuan
 */
public class AdvertisementSummary extends javax.swing.JFrame {

  
    private DefaultListModel allContent;
    /**
     * Creates new form AdvertisementSummary
     */
    public AdvertisementSummary()  {
        initComponents();
        Content();
    }

    
    
    
    
    public void Content(){
       
        allContent= new DefaultListModel();
        
        String selectCategory ="create view AdvertisementContent as select a.advertisement_pay,"
                                      + "a.advertisement_brand, p.user_ID " 
                                        + "from Post p, Advertisement a where a.post_ID = p.POST_ID";           
        
        ResultSet rs;
        try {
           
            DatabaseManager.getInstance().update(selectCategory);
            rs = DatabaseManager.getInstance().query("select * from AdvertisementContent");
            
             while (rs.next()){
                String a = rs.getString("user_ID");
                String b= rs.getString("advertisement_pay");
                String c= rs.getString("advertisement_brand");
                String str= a+ "                 "+ b +"                "+ c;
                allContent.addElement(str);
            
            } 
            DatabaseManager.getInstance().update("drop view AdvertisementContent");
            jList1.setModel(allContent);
            jList1.setVisible(true);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AdvertisementSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
    
           
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusTraversalKeysEnabled(false);
        setFocusableWindowState(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Advertisement Summary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 460, 50));

        jLabel2.setText("UserInfo                   AdvertisementFee                                    AdvertisementBrand");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 562, -1));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, 562, 273));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
