/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.Supervisor;
import Networkingapp.Database.DatabaseManager;
import Networkingapp.User.UserPosts;

import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;


/**
 *
 * @author Linda <lujiecanada@gmail.com>
 */
public class MessagerQuery extends javax.swing.JFrame {

    
    private DefaultListModel allAsc;
    private DefaultListModel allDesc;
    /**
     * Creates new form MessagerQuery
     */
    public MessagerQuery() {
        initComponents();
        myPostsList.setVisible(false);
        
    
        initialAsc();
        
        allPostsList.setModel(allAsc);
        
        initialDesc();
        myPostsList.setModel(allDesc);
    }

    
    
     private void initialAsc(){
        allAsc = new DefaultListModel();
        String selectPostStr = "select send_message_writerID, send_message_receiverID, count(*) from Send_Message group by send_message_writerID, send_message_receiverID order by count(*) ASC";
        ResultSet rs;
        try{
            rs = DatabaseManager.getInstance().query(selectPostStr);
      
            while (rs.next()){
                String smw = rs.getString("send_message_writerID");
                String smr = rs.getString("send_message_receiverID");
                String count = rs.getString("count(*)");
                String str = smw+"              "+smr+"                 "+count;
                allAsc.addElement(str);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(MessagerQuery.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
     
     
    private void initialDesc(){
     
            allDesc = new DefaultListModel();
            String selectPostStr = "select send_message_writerID, send_message_receiverID, count(*) from Send_Message group by send_message_writerID, send_message_receiverID order by count(*) DESC";    
            ResultSet rs;
        try {
            rs = DatabaseManager.getInstance().query(selectPostStr);
            while (rs.next()){
                String smw = rs.getString("send_message_writerID");
                String smr = rs.getString("send_message_receiverID");
                String count = rs.getString("count(*)");
                String str = smw+"              "+smr+"                 "+count;
                allDesc.addElement(str);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(MessagerQuery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allPostsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        myPostsList = new javax.swing.JList<>();
        ViewMyPostButton = new javax.swing.JButton();
        ViewAllPostButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setText("Message");

        jLabel9.setText("Writer_ID          Receriver_ID               Count                                                                                                                                ");

        allPostsList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allPostsList.setValueIsAdjusting(true);
        jScrollPane1.setViewportView(allPostsList);

        myPostsList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(myPostsList);

        ViewMyPostButton.setText("Descending");
        ViewMyPostButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMyPostButtonMouseClicked(evt);
            }
        });

        ViewAllPostButton.setText("Ascending");
        ViewAllPostButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAllPostButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(340, 340, 340)
                                    .addComponent(ViewAllPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(ViewMyPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewAllPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewMyPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewMyPostButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMyPostButtonMouseClicked
        allPostsList.setVisible(false);
        jScrollPane1.setVisible(false);
        myPostsList.setVisible(true);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_ViewMyPostButtonMouseClicked

    private void ViewAllPostButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllPostButtonMouseClicked
        jScrollPane1.setVisible(true);
        allPostsList.setVisible(true);
        myPostsList.setVisible(false);
        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_ViewAllPostButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessagerQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessagerQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessagerQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessagerQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessagerQuery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewAllPostButton;
    private javax.swing.JButton ViewMyPostButton;
    private javax.swing.JList<String> allPostsList;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> myPostsList;
    // End of variables declaration//GEN-END:variables
}
