/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.Supervisor;

import Networkingapp.Database.DatabaseManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Linda <lujiecanada@gmail.com>
 */
public class SupervisorPost extends javax.swing.JFrame {
      
    private DefaultListModel managedPosts;
    String supervisorID;
    
    /**
     * Creates new form SupervisorPost
     */
    public SupervisorPost(String supervisorID) {
        initComponents();
         this.supervisorID = supervisorID;
        
        initialAllPosts();
        ManagedPostList.setModel(managedPosts);
    }
    
    private void initialAllPosts(){
        managedPosts = new DefaultListModel();
        String selectPostStr = "select P.post_Id, P.post_title, P.post_time, P.post_content, P.user_ID "
                + "from Post P, Supervise S WHERE P.post_ID = S.post_ID and S.supervisor_ID = '"+ supervisorID +"'";
        ResultSet rs;
        try {
            rs = DatabaseManager.getInstance().query(selectPostStr);
            while (rs.next()){
               String pID = rs.getString("post_ID");
               String title = rs.getString("post_title");
               String time = rs.getString("post_time");
               String content = rs.getString("post_content");
               String uID = rs.getString("user_ID");
               
               int n = (80 - title.length()); 
               char[] repeat = new char[n];
               Arrays.fill(repeat, ' ');
               String str = pID+"  "+uID+"  "+time+"   "+ title+ new String(repeat) + content;
               managedPosts.addElement(str);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupervisorPost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabelBar = new javax.swing.JLabel();
        DeletePostButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManagedPostList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(920, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Title.setText("Managed Posts");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        jLabelBar.setText("PostID            UserID               Time              Title                                                                     Content                                                     ");
        getContentPane().add(jLabelBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 860, 30));

        DeletePostButton.setText("Delete Post");
        DeletePostButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletePostButtonMouseClicked(evt);
            }
        });
        getContentPane().add(DeletePostButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 180, 30));

        ManagedPostList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManagedPostList.setValueIsAdjusting(true);
        jScrollPane1.setViewportView(ManagedPostList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 920, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeletePostButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletePostButtonMouseClicked
        new Delete(supervisorID).setVisible(true);
    }//GEN-LAST:event_DeletePostButtonMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletePostButton;
    private javax.swing.JList<String> ManagedPostList;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabelBar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
