/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.User;

import Networkingapp.Database.DatabaseManager;
import com.sun.xml.internal.ws.util.StringUtils;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import static oracle.net.aso.C09.n;

/**
 *
 * @author Linda <lujiecanada@gmail.com>
 */
public class UserPosts extends javax.swing.JFrame {

    /**
     * Creates new form Posts
     */
    private DefaultListModel allPosts;
    private DefaultListModel myPosts;
    String userID;
    
    public UserPosts(String userID) {
        initComponents();
        myPostsList.setVisible(false);
        this.userID = userID;
        
        initialAllPosts();
        allPostsList.setModel(allPosts);
        initialMyPosts();
        myPostsList.setModel(myPosts);
    }
    
    private void initialAllPosts(){
        allPosts = new DefaultListModel();
        String selectPostStr = "select * from Post";
        ResultSet rs;
        try {
            rs = DatabaseManager.getInstance().query(selectPostStr);
            while (rs.next()){
               String pID = rs.getString("post_ID");
               String title = rs.getString("post_title");
               String time = rs.getString("post_time");
               String content = rs.getString("post_content");
               String uID = rs.getString("user_ID");
               
               int n = (80 - title.length()); 
               char[] repeat = new char[n];
               Arrays.fill(repeat, ' ');
               String str = pID+"  "+uID+"  "+time+"   "+ title+ new String(repeat) + content;
               allPosts.addElement(str);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserPosts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void initialMyPosts(){
        myPosts = new DefaultListModel();
        String selectPostStr = "select* From Post Where user_ID = " + "'" + userID + "'";
        ResultSet rs;
        try {
            rs = DatabaseManager.getInstance().query(selectPostStr);
        while (rs.next()){
           String pID = rs.getString("post_ID");
           String title = rs.getString("post_title");
           String time = rs.getString("post_time");
           String content = rs.getString("post_content");
           String uID = rs.getString("user_ID");
           int n = (80 - title.length()); 
           char[] repeat = new char[n];
           Arrays.fill(repeat, ' ');
           String str = pID+"  "+uID+"  "+time+"   "+ title+ new String(repeat) + content;
           myPosts.addElement(str);
        }
        } catch (SQLException ex) {
            Logger.getLogger(UserPosts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allPostsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        myPostsList = new javax.swing.JList<>();
        ViewMyPostButton = new javax.swing.JButton();
        ViewAllPostButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Posts");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setText("Posts");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 95, 34));

        jLabel9.setText("PostID            UserID               Time              Title                                                                     Content                                                     ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 860, 30));

        allPostsList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allPostsList.setValueIsAdjusting(true);
        jScrollPane1.setViewportView(allPostsList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 920, 440));

        myPostsList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(myPostsList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 920, 440));

        ViewMyPostButton.setText("View My Posts");
        ViewMyPostButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMyPostButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ViewMyPostButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 180, 30));

        ViewAllPostButton.setText("View All Posts");
        ViewAllPostButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAllPostButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ViewAllPostButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewMyPostButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMyPostButtonMouseClicked
        allPostsList.setVisible(false);
        jScrollPane1.setVisible(false);
        myPostsList.setVisible(true);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_ViewMyPostButtonMouseClicked

    private void ViewAllPostButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllPostButtonMouseClicked
        jScrollPane1.setVisible(true);
        allPostsList.setVisible(true);
        myPostsList.setVisible(false);
        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_ViewAllPostButtonMouseClicked

    /**
     * @param args the command line arguments
    **/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewAllPostButton;
    private javax.swing.JButton ViewMyPostButton;
    private javax.swing.JList<String> allPostsList;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> myPostsList;
    // End of variables declaration//GEN-END:variables
}
