/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.User;

/**
 *
 * @author Linda <lujiecanada@gmail.com>
 */
public class UserMain extends javax.swing.JFrame {

    /**
     * Creates new form UserMain
     */
    public UserMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editProfile_frame = new javax.swing.JInternalFrame();
        save_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userName_txt = new javax.swing.JFormattedTextField();
        gender_txt = new javax.swing.JFormattedTextField();
        age_txt = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address_txt = new javax.swing.JTextArea();
        bg_panel = new javax.swing.JPanel();
        myPost_button = new javax.swing.JButton();
        allPost_button = new javax.swing.JButton();
        editProfile_button = new javax.swing.JButton();
        msg_button = new javax.swing.JButton();
        userID_label = new javax.swing.JLabel();
        select_uID = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        display_textPane1 = new javax.swing.JTextPane();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Main Page");
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(null);

        editProfile_frame.setBackground(new java.awt.Color(255, 255, 255));
        editProfile_frame.setClosable(true);
        editProfile_frame.setTitle("Edit Profile");
        editProfile_frame.setVisible(false);

        save_button.setText("Save");

        cancel_button.setText("Cancel");

        jLabel1.setText("User Name");

        jLabel2.setText("Gender");

        jLabel3.setText("Age");

        jLabel4.setText("About Yourself");

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Not required, but suggest to fill in information.");

        Address_txt.setColumns(20);
        Address_txt.setLineWrap(true);
        Address_txt.setRows(5);
        jScrollPane1.setViewportView(Address_txt);

        javax.swing.GroupLayout editProfile_frameLayout = new javax.swing.GroupLayout(editProfile_frame.getContentPane());
        editProfile_frame.getContentPane().setLayout(editProfile_frameLayout);
        editProfile_frameLayout.setHorizontalGroup(
            editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfile_frameLayout.createSequentialGroup()
                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(editProfile_frameLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editProfile_frameLayout.createSequentialGroup()
                                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editProfile_frameLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel4))
                                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editProfile_frameLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(userName_txt)
                                            .addComponent(age_txt)
                                            .addComponent(gender_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                                    .addGroup(editProfile_frameLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5))
                        .addGap(5, 5, 5))
                    .addGroup(editProfile_frameLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(save_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel_button)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        editProfile_frameLayout.setVerticalGroup(
            editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfile_frameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editProfile_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_button)
                    .addComponent(cancel_button))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(editProfile_frame);
        editProfile_frame.setBounds(10, 10, 390, 381);

        bg_panel.setBackground(new java.awt.Color(255, 255, 255));
        bg_panel.setLayout(null);

        myPost_button.setText("My Post");
        myPost_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myPost_buttonMouseClicked(evt);
            }
        });
        bg_panel.add(myPost_button);
        myPost_button.setBounds(470, 70, 93, 29);

        allPost_button.setText("All Post");
        allPost_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allPost_buttonMouseClicked(evt);
            }
        });
        bg_panel.add(allPost_button);
        allPost_button.setBounds(470, 110, 92, 29);

        editProfile_button.setText("Edit Profile");
        editProfile_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfile_buttonMouseClicked(evt);
            }
        });
        bg_panel.add(editProfile_button);
        editProfile_button.setBounds(470, 210, 112, 29);

        msg_button.setText("Message");
        msg_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msg_buttonMouseClicked(evt);
            }
        });
        bg_panel.add(msg_button);
        msg_button.setBounds(470, 160, 98, 29);

        userID_label.setText("User ID:");
        bg_panel.add(userID_label);
        userID_label.setBounds(44, 29, 50, 16);

        select_uID.setText("jLabel2");
        bg_panel.add(select_uID);
        select_uID.setBounds(112, 29, 45, 16);

        logout_button.setText("Logout");
        bg_panel.add(logout_button);
        logout_button.setBounds(470, 300, 88, 29);

        display_textPane1.setEditable(false);
        display_textPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Profile"));
        jScrollPane2.setViewportView(display_textPane1);

        bg_panel.add(jScrollPane2);
        jScrollPane2.setBounds(40, 70, 383, 263);

        getContentPane().add(bg_panel);
        bg_panel.setBounds(80, 50, 600, 370);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Networkingapp/Pictures/User-Main-background.jpg"))); // NOI18N
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 760, 460);

        setSize(new java.awt.Dimension(760, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myPost_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myPost_buttonMouseClicked
        // TODO add your handling code here:
        dispose();
        new MyPost().setVisible(true);
        
    }//GEN-LAST:event_myPost_buttonMouseClicked

    private void allPost_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allPost_buttonMouseClicked
        // TODO add your handling code here:
        dispose();
        new AllPost().setVisible(true);
    }//GEN-LAST:event_allPost_buttonMouseClicked

    private void msg_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msg_buttonMouseClicked
        // TODO add your handling code here:
        dispose();
        new Message().setVisible(true);
    }//GEN-LAST:event_msg_buttonMouseClicked

    private void editProfile_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfile_buttonMouseClicked
        // TODO add your handling code here:
        
        editProfile_frame.setVisible(true);
        
    }//GEN-LAST:event_editProfile_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address_txt;
    private javax.swing.JFormattedTextField age_txt;
    private javax.swing.JButton allPost_button;
    private javax.swing.JLabel bg_label;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JButton cancel_button;
    private javax.swing.JTextPane display_textPane1;
    private javax.swing.JButton editProfile_button;
    private javax.swing.JInternalFrame editProfile_frame;
    private javax.swing.JFormattedTextField gender_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton msg_button;
    private javax.swing.JButton myPost_button;
    private javax.swing.JButton save_button;
    private javax.swing.JLabel select_uID;
    private javax.swing.JLabel userID_label;
    private javax.swing.JFormattedTextField userName_txt;
    // End of variables declaration//GEN-END:variables
}
