/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Networkingapp.User;

import Networkingapp.Connector.CategoryConnector;
import Networkingapp.Connector.PostConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author peichen
 */
public class UserPost extends javax.swing.JFrame {

    /**
     * Creates new form MyPost
     */
    
    private static int postMode;
    
    public UserPost() {
        postMode = 0;
        initComponents();
        initPost(postMode);
    }
    
    // (mode == 0) AllPost
    // (mode == 1) MyPost
    private void initPost(int mode){
        ResultSet res0;
        ResultSet res1;
        res0 = PostConnector.getPost(mode);
        res1 = CategoryConnector.getCategory(mode);
        
        DefaultTableModel model = (DefaultTableModel) postTable.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        
        try {
            while(res0.next()){
                String pID = res0.getString("post_ID");
                String pTitle = res0.getString("post_title");
                String pTime = res0.getString("post_time");
                String cName = "";
                if(res1.next())
                    cName += res1.getString("category_Name");
        
                String uID = res0.getString("user_ID");
                
                Object[]rowData  = new Object[] {pID, pTitle, uID, cName, pTime};
                //Object[]rowData  = new Object[] {"1", "2", "3", "Category", "4"};
                model = (DefaultTableModel) postTable.getModel();
                model.addRow(rowData);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserPost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
//    public void initMyPost(){
//        ResultSet res = PostConnector.getMyPost();
//
//        
//        try {
//            while(res.next()){
//                String pID = res.getString("post_ID");
//                String pTitle = res.getString("post_title");
//                String pTime = res.getString("post_time");
//                
//                String uID = res.getString("user_ID");
//                
//                Object[]rowData  = new Object[] {pID, pTitle, uID, "Category", pTime};
//                //Object[]rowData  = new Object[] {"1", "2", "3", "Category", "4"};
//                DefaultTableModel model = (DefaultTableModel) postTable.getModel();
//                model.addRow(rowData);
//                
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(UserPost.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentDsiplay = new javax.swing.JTextArea();
        allPost_button = new javax.swing.JButton();
        myPost_button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        postTable = new javax.swing.JTable();
        deletePost_button = new javax.swing.JButton();
        goback_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Post");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Welcome to Post"));
        jPanel1.setToolTipText("");

        jLabel1.setText("Search");

        jLabel2.setText("by");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose...", "User Name/ID", "Post ID", "Title", "Time", "Content" }));

        jButton1.setText("Search");

        contentDsiplay.setColumns(20);
        contentDsiplay.setFont(new java.awt.Font("Toppan Bunkyu Mincho", 0, 24)); // NOI18N
        contentDsiplay.setLineWrap(true);
        contentDsiplay.setRows(5);
        jScrollPane2.setViewportView(contentDsiplay);

        allPost_button.setText("All Posts");
        allPost_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allPost_buttonMouseClicked(evt);
            }
        });

        myPost_button.setText("My post");
        myPost_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myPost_buttonMouseClicked(evt);
            }
        });

        jButton4.setText("Edit Post");

        jButton5.setText("Create Post");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        postTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Post ID", "Title", "User ID", "Category", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        postTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(postTable);

        deletePost_button.setText("Delete Post");
        deletePost_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePost_buttonMouseClicked(evt);
            }
        });

        goback_button.setText("Go Back");
        goback_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goback_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(allPost_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(myPost_button)
                                .addGap(45, 45, 45)
                                .addComponent(jButton4)
                                .addGap(34, 34, 34)
                                .addComponent(jButton5)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deletePost_button)
                                .addGap(33, 33, 33)
                                .addComponent(goback_button)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allPost_button)
                    .addComponent(myPost_button)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(deletePost_button)
                    .addComponent(goback_button))
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(66, 50, 911, 488);

        setSize(new java.awt.Dimension(1040, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        new CreatePost().setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void postTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postTableMouseClicked
        // TODO add your handling code here:
       
        if(postTable.getSelectedRow() != -1){
            initContent(postTable.getValueAt(postTable.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_postTableMouseClicked

    private void myPost_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myPost_buttonMouseClicked
        // TODO add your handling code here:
        postMode = 1;
//        DefaultTableModel model = (DefaultTableModel) postTable.getModel();
//        int rowCount = model.getRowCount();
//        for (int i = rowCount - 1; i >= 0; i--) {
//            model.removeRow(i);
//        }

        initPost(postMode);
        repaint();
    }//GEN-LAST:event_myPost_buttonMouseClicked

    private void allPost_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allPost_buttonMouseClicked
        // TODO add your handling code here:
        
        postMode = 0;
//        DefaultTableModel model = (DefaultTableModel) postTable.getModel();
//
//        int rowCount = model.getRowCount();
//        for (int i = rowCount - 1; i >= 0; i--) {
//            model.removeRow(i);
//        }

        initPost(postMode);
        repaint();
    }//GEN-LAST:event_allPost_buttonMouseClicked

    private void goback_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goback_buttonMouseClicked
        // TODO add your handling code here:
        dispose();
        try {
            new UserMain().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(UserPost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_goback_buttonMouseClicked

    private void deletePost_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePost_buttonMouseClicked
        // TODO add your handling code here:
        int[] index = postTable.getSelectedRows();
        //System.out.println(index.length);
        String pID;
        if (index.length > 0){
            for(int i = 0; i < index.length; i++){
                pID = postTable.getValueAt(index[i], 0).toString();
                if(pID.equals("")){
                    return;
                }else{
                    PostConnector.delPost(pID);
                }
            }
        }
        initPost(postMode);
        repaint();

    }//GEN-LAST:event_deletePost_buttonMouseClicked

    private void initContent(String postID){
        
        String pContent = PostConnector.getSelectedContent(postID);
        contentDsiplay.setText(pContent);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allPost_button;
    private javax.swing.JTextArea contentDsiplay;
    private javax.swing.JButton deletePost_button;
    private javax.swing.JButton goback_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton myPost_button;
    private javax.swing.JTable postTable;
    // End of variables declaration//GEN-END:variables
}
